### ISSUE TITLE
[BRAINSTORM] Configuration paths and Formats

### ISSUE THREAD

**Issue by cedricziel** [ipf/TYPO3.Surf#1]
Surf should become a truly independant deployment tool, thus the separation from Flow and the desire to package as `phar`.

To configure it, there are several possible paths:

```
# global configuration?
~/.typo3/surf/config.yml

# project specific configuration?
~/project/.typo3-surf.yml
```

I could imagine the project conf overriding or extending the global configuration in terms of:

* where are the surf tasks located
* which environment should be used [dev/stage/prod/..]
* set env vars for further configuration of the tasks regarding credentials

Please add your ideas :)

**Comment by mblaschke** [comment]
YML should be fine, please no JSON (no comments possible in JSON)
Most basic tasks should be included -> advanced tasks could/should be loaded from local phar/directory with autoloading?!
